# Generated by Django 3.1.7 on 2021-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20210306_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
