# Generated by Django 3.1.7 on 2021-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20210306_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('user_id', models.CharField(max_length=200, null=True)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('price', models.SmallIntegerField()),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='XS', max_length=20)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('units', models.SmallIntegerField()),
            ],
        ),
    ]
