# Generated by Django 3.1.7 on 2021-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_cartitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
