# Generated by Django 3.1.7 on 2021-03-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
