# Generated by Django 3.1.7 on 2021-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
