# Generated by Django 3.1.7 on 2021-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_cartitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=200, null=True)),
                ('item_id', models.SmallIntegerField()),
                ('user_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
